name: Build XInput firmware

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install ARM toolchain
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi make

    - name: Build firmware
      run: make

    - name: Upload HEX output
      uses: actions/upload-artifact@v3
      with:
        name: xinput_firmware
        path: |
          *.hex
